### ISSUE TITLE
CF Template - Create Necessary Params

### ISSUE THREAD

**Issue by jrsalgado** [jrsalgado/cdk-athena-quicksight#2]
Investigate common params and create their CF Params section according to common santander Env params and specific project params,  this params are required to deploy on Sanbox(Fidel account) environment and/or Santander, some of this params may be resolved by Edgar

```yaml
Parameters:
  Project:
    Type: String
    Default: test
    Description: Name of the project for the tag
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - stg
      - pre
      - ocu
      - sha
      - prod
    Description: Name of the environment for the tag
  Country:
    Type: String
    AllowedValues:
      - es
      - de
      - pt
      - nl
      - ar
      - mc
      - mx
      - us
    Description: Name of the country for the tag
  QuickSightUsername:
    Type: String
    Default: master
    ConstraintDescription: QuickSight username must be between 5 and 20 characters
    Description: Quicksight username
    MaxLength: 20
    MinLength: 5
  AthenaDatabaseName:
    Type: String
    Default: santander
    Description: Athena Database Name used for QS dataset queries
  AthenaWorkgroupName:
    Type: String
    Description: Athena Workgorup name
```
